services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

#  nest:
#    container_name: nest
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "3333:3333"
#    depends_on:
#      - postgres
#    environment:
#      DATABASE_URL: "postgresql://postgres:docker@postgres:5432/nest?schema=public"
#    volumes:
#      - .:/app